# Generated by Django 5.1.7 on 2025-03-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.CharField(default='dasfasf', max_length=255),
            preserve_default=False,
        ),
    ]
