# Generated by Django 5.1.7 on 2025-03-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBlog', '0002_alter_panier_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='item_count',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
