# Generated by Django 5.1.7 on 2025-03-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBlog', '0003_panier_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='item_count',
        ),
    ]
