# Generated by Django 5.1.7 on 2025-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomBlog', '0004_remove_panier_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1.2, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
